config/routes.rb
Rails.application.routes.draw do

  # Devise, User
  devise_for :users

  # CodePosts
  resources :code_posts # For EDIT
  get 'code/datatable_ajax', to: 'code_posts#datatable_ajax'
  get 'code/new', to: 'code_posts#new', as: 'new_code'
  get 'code/published', to: 'code_posts#published', as: 'published_code'
  get 'code/edit/:id', to: 'code_posts#edit', as: 'edit_code'

  # Voting
  get 'code/:id/upvote', to: 'code_posts#upvote', as: 'upvote_code'
  get 'code/:id/downvote', to: 'code_posts#downvote', as: 'downvote_code'

  get 'code/:id/delete', to: 'code_posts#destroy', as: 'delete_code'
  get 'code/:id', to: 'code_posts#show', as: 'show_code'
  get 'code/', to: 'code_posts#index', as: 'code'

  root 'code_posts#index' # ROOT
  get '*path', to: 'static_pages#home' # If page not found

end

app/models/category.rb
class Category
  # Categories getter
  def self.get_categories
    ["Sorting", "Dynamic Programming", "Other"]
  end

  # Categories count getter
  def self.count
    get_categories.count
  end
end

app/models/code_language.rb
class CodeLanguage

  # Languages getter
  def self.get_languages
    ["C", "C++", "C#", "Java", "Ruby", "Python", "PHP", "JavaScript",
       "Swift", "Objective-C", "Perl", "Ada", "Lisp"]
  end

  def self.get_languages_modes
    ["c_cpp", "c_cpp", "csharp", "java", "ruby", "python", "php", "javascript",
    "swift", "objectivec", "perl", "ada", "lisp"]
  end

  # Languages count getter
  def self.count
    get_languages.count
  end
end

app/models/code_post.rb
class CodePost < ActiveRecord::Base

  validates_uniqueness_of [:title, :code]
  validates_presence_of [:title, :code, :category, :code_language]
  scope :available, -> { where(deleted_at: nil) } # Not deleted CodePost scope
  scope :upvoted, -> { order('upvotes DESC') }

  def get_email
    user = User.find_by(id: self.user_id)
    unless user.nil?
      user.email
    else
      "example@gmail.com"
    end
  end

  def get_language
    CodeLanguage.get_languages[self.code_language.to_i]
  end

  def get_language_mode_code
    CodeLanguage.get_languages_modes[self.code_language.to_i]
  end

  def get_reputation
    count = self.upvotes.count - self.downvotes.count
    if self.reputation != count # If refresh is needed
      self.reputation = count
      self.save
    end
    count
  end

  def get_reputation_html
    if self.get_reputation < 0
      ("<span class='text-red'>#{self.get_reputation}</span>").html_safe
    else
      ("<span class='text-green'>#{self.get_reputation}</span>").html_safe
    end
  end

  # Upvoting
  def do_upvote(id = nil)
    if !id.nil? # Not nil
      unless self.upvotes.include?(id)
        self.downvotes.delete(id)
        self.upvotes << id
        self.save
      end
    end
  end

  # Downvoting
  def do_downvote(id = nil)
    if !id.nil? # Not nil
      unless self.downvotes.include?(id)
        self.upvotes.delete(id)
        self.downvotes << id
        self.save
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_admin?
    self.user_type == "admin"
  end

  def available_posts_count
    CodePost.available.where(user_id: self.id).count;
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/code_posts_controller.rb
class CodePostsController < ApplicationController

  helper_method :is_owner? # Helper method for views
  before_action :authenticate_user!, only: [:new, :edit, :published, :upvote, :downvote]
  before_action :set_code_post, only: [:destroy, :show, :edit, :update, :upvote, :downvote]
  before_action :set_votes, only: [:upvote, :downvote, :show] # Get Vote Values

  def index
    @code_posts = CodePost.available.upvoted.all # Get all non deleted Code posts
  end

  def datatable_ajax
    render json: CodePostDatatable.new(view_context)
  end

  def upvote
    @code_post.do_upvote(current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def downvote
    @code_post.do_downvote(current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def published
    # Get all non deleted and published by owner Code Posts
    @code_posts = CodePost.available.where(user_id: current_user).all
    render 'index' # Render default view
  end

  def show
    # TODO
  end

  def new
    @code_post = CodePost.new # New Code Post
  end

  def edit
    redirect_to root_path unless is_owner?(@code_post)
  end

  def create
    @code_post = CodePost.new(code_post_params)
    @code_post.user_id = current_user.id # Setting whom will belong to
    @code_post.upvotes << current_user.id # Add upvote after creation

    respond_to do |format|
      if @code_post.save
        format.html { redirect_to show_code_path(@code_post), notice: "Code created successfully!"}
        format.json { render :show, status: created, location: @code_post }
      else
        format.html { render :new }
        format.json { render json: @code_post.errors, status: :unproccesable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @code_post.update(code_post_params)
        format.html { redirect_to show_code_path(@code_post), notice: "Code updated successfully!"}
        format.json { render :show, status: created, location: @code_post }
      else
        format.html { render :edit }
        format.json { render json: @code_post.errors, status: :unproccesable_entity }
      end
    end
  end

  def destroy
    if is_owner?(@code_post) || current_user.is_admin?
      #@code_post.deleted_at = DateTime.now
      #@code_post.save
      @code_post.destroy
      respond_to do |format|
        format.html { redirect_to code_path, notice: "Code deleted successfully!"}
        format.json { head :no_content }
      end
    else
      redirect_to root_path
    end
  end

  private

    # Set votes
    def set_votes
      @upvotes = @code_post.upvotes.count
      @downvotes = @code_post.downvotes.count
    end

    # Owner of chosen CodePost?
    def is_owner?(code_post)
      code_post.user_id == current_user.id unless current_user.nil?
    end

    # Setting code_post before action
    def set_code_post
      @code_post = CodePost.find(params[:id])
    end

    # Strong params
    def code_post_params
      params.require(:code_post).permit(:title, :code,
      :category, :code_language)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_database_count
    CodePost.available.count
  end

  def is_devise_controller?
    params[:controller].include?("devise");
  end

  def get_logo_text
    ("<b>CODE</b>FULL").html_safe
  end

  def get_logo_text_small
    ("<b>C</b>FL").html_safe
  end
end

app/helpers/code_posts_helper.rb
module CodePostsHelper
end

app/views/code_posts/_editorscripts.html.erb
<!-- <script src="src/ace.js" type="text/javascript" charset="utf-8"></script> -->
<script>
  var editor = ace.edit("editor");
  var textarea = $('#code_post_code');
  editor.setTheme("ace/theme/eclipse");
  editor.getSession().setMode("ace/mode/<%= @code_post.get_language_mode_code %>");
  editor.setShowPrintMargin(false);
  editor.getSession().on('change', function () {
    textarea.val(editor.getSession().getValue());
  });
  textarea.val(editor.getSession().getValue());
</script>

app/views/code_posts/_form.html.erb
<%= simple_form_for(@code_post) do |f| %>
<section class="content">
  <div class="row">
    <div class="col-xs-8">
      <div class="box">
          <div id="editor"><%= @code_post.code %></div>
          <textarea name="code_post[code]" id="code_post_code" hidden="true"><%= @code_post.code %></textarea>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="box box-default">
        <div class="box-header">
          <h3 class="box-title"><%= fa_icon "question-circle-o", text: " Other information" %></h3>
          <%= render 'layouts/collapsers' %>
        </div>
        <div class="box-body">
          <div class="table-responsive">
              <table class="table no-margin">
                <tr>
                  <td align="right" width="10%"><%= fa_icon "laptop"%></td>
                  <td>Title</td>
                  <td><%= f.input :title, label: false, input_html: { style:'width:100%' } %></td>
                </tr>
                <tr>
                  <td align="right"><%= fa_icon "folder-o"%></td>
                  <td>Category</td>
                  <td><%= f.select :category, Category.get_categories, {}, style: 'width:100%' %></td>
                </tr>
                <tr>
                  <td align="right"><%= fa_icon "code"%></td>
                  <td>Language</td>
                  <td>
                    <%= f.select :code_language, CodeLanguage.get_languages.each_with_index.map { |name, index| [name, index] }, {}, style: 'width:100%' %>
                  </td>
                </tr>
              </table>
          </div>
        </div>
        <div class="box-footer">
          <%= f.button :submit, "Submit" %>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/code_posts/_info_table.html.erb
<table class="table no-margin">
  <tr>
    <td align="right" width="10%"><%= fa_icon "folder-o"%></td>
    <td>Category</td>
    <td><%= @code_post.category %></td>
  </tr>
  <tr>
    <td align="right"><%= fa_icon "code"%></td>
    <td>Language</td>
    <td><%= @code_post.get_language %></td>
  </tr>
  <tr>
    <td align="right"><%= fa_icon "star"%></td>
    <td>Reptutation</td>
    <td><%= @code_post.get_reputation_html %></td>
  </tr>
  <tr>
    <td align="right"><%= fa_icon "upload"%></td>
    <td>Owner</td>
    <td><%= @code_post.get_email %></td>
  </tr>
</table>

app/views/code_posts/_votes.html.erb
<div class="pull-left">
  <p>
  <%= link_to upvote_code_path(@code_post), remote: true do %>
    Upvote
    <%= fa_icon "chevron-up" %>
  <% end %>
  </p>
</div>
<div class="pull-right">
  <p>
  <%= link_to downvote_code_path(@code_post), remote: true do %>
    Downvote
    <%= fa_icon "chevron-down" %>
  <% end %>
  </p>
</div>

app/views/code_posts/downvote.js.erb
$("#reputation-ajax").html("<%= escape_javascript(render 'info_table') %>");

app/views/code_posts/edit.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <%= render 'layouts/alerts' %>

  <section class="content-header">
    <h1><%= @code_post.title %></h1>
    <ol class="breadcrumb">
      <li><a href="<%= root_path %>">
        <%= fa_icon "clone", text: "Home" %>
        </a>
      </li>
      <li><a href="<%= code_path %>">Database</a></li>
      <li class="active"><a href="<%= show_code_path(@code_post) %>"><%= @code_post.id %></a> (EDIT)</li>
    </ol>
  </section>

<%= render 'form' %>

</div>
<!-- /.content-wrapper -->

<%= render 'editorscripts' %>

app/views/code_posts/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <%= render 'layouts/alerts' %>

  <section class="content-header">
    <br>
    <ol class="breadcrumb">
      <li><a href="<%= root_path %>">
        <%= fa_icon "clone", text: "Home" %>
        </a>
      </li>
      <li class="active">Database</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-body">
            <table id="database-table" class="display responsive no-wrap">
              <thead>
              <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Language</th>
                <th>Reputation</th>
              </tr>
              </thead>

              <tbody>
              </tbody>

              <tfoot>
                <tr>
                  <th>Title</th>
                  <th>Category</th>
                  <th>Language</th>
                  <th>Reputation</th>
                </tr>
              </tfoot>

            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
  $('#database-table').DataTable({
    "processing": true,
    "serverSide": true,
    "ajax": "code/datatable_ajax/"
  });
</script>

app/views/code_posts/new.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <%= render 'layouts/alerts' %>
  <section class="content-header">
    <h1>Publish Code</h1>
    <ol class="breadcrumb">
      <li><a href="<%= root_path %>">
        <%= fa_icon "clone", text: "Home" %>
        </a>
      </li>
      <li><a href="<%= code_path %>">Database</a></li>
      <li class="active">(NEW)</li>
    </ol>
  </section>

<%= render 'form' %>

</div>
<!-- /.content-wrapper -->

<%= render 'editorscripts' %>

app/views/code_posts/show.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <%= render 'layouts/alerts' %>
  
  <section class="content-header">
    <h1><%= @code_post.title %><% if !current_user.nil? && (is_owner?(@code_post) || current_user.is_admin?) %>
          <%= link_to edit_code_path(@code_post) do %>
            <%= fa_icon "pencil" %>
          <% end %>
        <% end %></h1>
    <ol class="breadcrumb">
      <li><a href="<%= root_path %>">
        <%= fa_icon "clone", text: "Home" %>
        </a>
      </li>
      <li><a href="<%= code_path %>">Database</a></li>
      <li class="active"><%= @code_post.id %> (VIEW)</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-md-8">
        <div class="box box-default">
          <div id="editor"><%= @code_post.code %></div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="box box-default">
          <div class="box-header">
            <h3 class="box-title"><%= fa_icon "question-circle-o", text: " Other information" %></h3>
            <%= render 'layouts/collapsers' %>
          </div>
          <div class="box-body">
            <div class="table-responsive">
              <div id="reputation-ajax">
                <%= render 'info_table' %>
              </div>
            </div>
          </div>
          <% unless current_user.nil? %>
          <div class="box-footer" style="padding-left: 17px;padding-right: 17px;">
            <%= render 'votes' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>


<script>
  var editor = ace.edit("editor");
  editor.setTheme("ace/theme/eclipse");
  editor.getSession().setMode("ace/mode/<%= @code_post.get_language_mode_code %>");
  editor.setShowPrintMargin(false);
  editor.setReadOnly(true);
</script>

app/views/code_posts/upvote.js.erb
$("#reputation-ajax").html("<%= escape_javascript(render 'info_table') %>");

app/views/layouts/_alerts.html.erb
<!-- Alerts -->
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
<%#= notice %>
<%#= alert %>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <% if name == "alert" %>
      <div class="alert alert-danger">
    <% else %>
      <div class="alert alert-success">
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_collapsers.html.erb
<div class="box-tools pull-right">
  <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
  </button>
</div>

app/views/layouts/_content.html.erb
<%= yield %>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <strong>&copy; Ugnius Skučas <%= DateTime.now.year %></strong>
  <div class="pull-right hidden-xs">
    <b>Version</b> 0.0.1
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <a href="<%= root_path %>" class="logo">
    <span class="logo-mini"><%= fa_icon "clone" %></span>
    <span class="logo-lg"><%= fa_icon "clone" %> <%= get_logo_text %></span>
  </a>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-left">
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>

      <li>
        <a href="<%= code_path %>">
          <i class="fa fa-table"></i>
          <span>Database (<%= get_database_count %>)</span></a>
      </li>

      <li class="header">USER NAVIGATION</li>
      <% unless current_user.nil? # LOGGED IN%>
      <li>
        <a href="<%= new_code_path %>">
          <%= fa_icon "edit" %>
          <span>Publish Code</span></a>
      </li>
      <li>
        <a href="<%= published_code_path %>">
          <%= fa_icon "cogs" %>
          <span>View Published Code (<%= current_user.available_posts_count %>)</span></a>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <%= fa_icon "sign-out" %>
          <span>Logout</span>
        <% end %>
      </li>
      <% else # LOGGED OFF %>
      <li>
        <%= link_to new_user_session_path do %>
          <%= fa_icon "sign-in" %>
          <span>Sign in</span>
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path do %>
          <%= fa_icon "lock" %>
          <span>Registration</span>
        <% end %>
      </li>
      <% end %>

      <li class="header">OTHER</li>
      <li>
        <a href="<%= code_path %>">
          <%= fa_icon "question" %>
          <span>About Grepfull</span></a>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CODEFULL - share your mind!</title>
  <%= favicon_link_tag '/favicon.ico' %>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<% unless is_devise_controller? # MAIN APPLICATION %>
  <body class="fixed hold-transition skin-black sidebar-mini">
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <%= render 'layouts/sidebar' %>
      <%= render 'layouts/content' %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
<% else #FOR LOGIN/SIGNUP %>
  <%= render 'layouts/alerts' %>
  <%= render 'layouts/content' %>
<% end %>
</html>

app/views/shared/navbar/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>